import { FetchCategory } from "@prisma/client";

export type CanonicalFetchTarget = {
  name: string;
  query: string;
  category: FetchCategory;
  priority: number;
  refreshEveryMinutes: number;
  roleNames: string[];
};

export const CANONICAL_FETCH_TARGETS: CanonicalFetchTarget[] = [
  {
    name: "Backend Developer",
    query: "Backend Developer",
    category: FetchCategory.ENGINEERING,
    priority: 120,
    refreshEveryMinutes: 360,
    roleNames: ["Backend Developer", "Software Engineer"],
  },
  {
    name: "Frontend Developer",
    query: "Frontend Developer",
    category: FetchCategory.ENGINEERING,
    priority: 118,
    refreshEveryMinutes: 360,
    roleNames: ["Frontend Developer", "React Developer"],
  },
  {
    name: "Full Stack Developer",
    query: "Full Stack Developer",
    category: FetchCategory.ENGINEERING,
    priority: 120,
    refreshEveryMinutes: 360,
    roleNames: ["Full Stack Developer", "Software Engineer"],
  },
  {
    name: "Software Engineer",
    query: "Software Engineer",
    category: FetchCategory.ENGINEERING,
    priority: 115,
    refreshEveryMinutes: 360,
    roleNames: ["Software Engineer"],
  },
  {
    name: "DevOps Engineer",
    query: "DevOps Engineer",
    category: FetchCategory.ENGINEERING,
    priority: 110,
    refreshEveryMinutes: 360,
    roleNames: ["DevOps Engineer"],
  },
  {
    name: "QA Engineer",
    query: "QA Engineer",
    category: FetchCategory.ENGINEERING,
    priority: 105,
    refreshEveryMinutes: 360,
    roleNames: ["QA Engineer", "Test Engineer"],
  },
  {
    name: "Product Manager",
    query: "Product Manager",
    category: FetchCategory.PRODUCT,
    priority: 112,
    refreshEveryMinutes: 360,
    roleNames: ["Product Manager"],
  },
  {
    name: "Project Manager",
    query: "Project Manager",
    category: FetchCategory.PRODUCT,
    priority: 108,
    refreshEveryMinutes: 360,
    roleNames: ["Project Manager"],
  },
  {
    name: "Program Manager",
    query: "Program Manager",
    category: FetchCategory.PRODUCT,
    priority: 104,
    refreshEveryMinutes: 360,
    roleNames: ["Program Manager"],
  },
  {
    name: "Business Analyst",
    query: "Business Analyst",
    category: FetchCategory.PRODUCT,
    priority: 102,
    refreshEveryMinutes: 360,
    roleNames: ["Business Analyst"],
  },
  {
    name: "HR Recruiter",
    query: "HR Recruiter",
    category: FetchCategory.HR,
    priority: 102,
    refreshEveryMinutes: 360,
    roleNames: ["HR Recruiter", "Recruiter", "Talent Acquisition"],
  },
  {
    name: "Talent Acquisition",
    query: "Talent Acquisition",
    category: FetchCategory.HR,
    priority: 100,
    refreshEveryMinutes: 360,
    roleNames: ["Talent Acquisition", "Recruiter"],
  },
  {
    name: "HR Generalist",
    query: "HR Generalist",
    category: FetchCategory.HR,
    priority: 96,
    refreshEveryMinutes: 360,
    roleNames: ["HR Generalist"],
  },
  {
    name: "Data Analyst",
    query: "Data Analyst",
    category: FetchCategory.DATA,
    priority: 108,
    refreshEveryMinutes: 360,
    roleNames: ["Data Analyst"],
  },
  {
    name: "Data Scientist",
    query: "Data Scientist",
    category: FetchCategory.DATA,
    priority: 105,
    refreshEveryMinutes: 360,
    roleNames: ["Data Scientist"],
  },
  {
    name: "Data Engineer",
    query: "Data Engineer",
    category: FetchCategory.DATA,
    priority: 104,
    refreshEveryMinutes: 360,
    roleNames: ["Data Engineer"],
  },
  {
    name: "UI UX Designer",
    query: "UI UX Designer",
    category: FetchCategory.DESIGN,
    priority: 98,
    refreshEveryMinutes: 360,
    roleNames: ["UI UX Designer", "Product Designer"],
  },
  {
    name: "Product Designer",
    query: "Product Designer",
    category: FetchCategory.DESIGN,
    priority: 96,
    refreshEveryMinutes: 360,
    roleNames: ["Product Designer", "UI UX Designer"],
  },
  {
    name: "Sales Executive",
    query: "Sales Executive",
    category: FetchCategory.SALES,
    priority: 92,
    refreshEveryMinutes: 360,
    roleNames: ["Sales Executive"],
  },
  {
    name: "Marketing Manager",
    query: "Marketing Manager",
    category: FetchCategory.MARKETING,
    priority: 92,
    refreshEveryMinutes: 360,
    roleNames: ["Marketing Manager"],
  },
  {
    name: "Operations Analyst",
    query: "Operations Analyst",
    category: FetchCategory.OPERATIONS,
    priority: 88,
    refreshEveryMinutes: 360,
    roleNames: ["Operations Analyst"],
  },
  {
    name: "Finance Analyst",
    query: "Finance Analyst",
    category: FetchCategory.FINANCE,
    priority: 88,
    refreshEveryMinutes: 360,
    roleNames: ["Finance Analyst"],
  },
];
